- hosts: webservers
  become: yes # make sure it runs as root
  vars: 
    http_port: 8000
    https_port: 4443
    html_welcome_msg: "Hello world"
  tasks:
    - include_tasks: tasks/apache2_install.yml

  handlers:
    - include_tasks: handlers/main.yml
